### ISSUE TITLE
Abkuerzungsverzeichnis verschwindet nach ein paar Aktualisierungen, Inhaltsverzeichnis nicht mehr korrekt

### ISSUE THREAD

**Issue by sineadsayo** [maknesium/latex-vorlage-diplom-bachelor-masterarbeiten#1]
Wenn man die "Hauptdatei.tex" ein paar mal nacheinander öffnet, verschwindet auf einmal das Abkuerzungsverzeichnis komplett und im Inhaltsverzeichnis steht eine arabische 1 anstatt einer römischen 5 (siehe Screenshot). Ich habe schon viel ausprobiert doch bin leider nicht in der Lage den Bug zu fixen. Könntest du mal drüberschauen? 
Danke im Voraus! :)

<img width="611" alt="Bildschirmfoto 2020-04-27 um 10 44 15" src="https://user-images.githubusercontent.com/44392697/80352586-63ca2f00-8874-11ea-8518-bc46888deb2b.png">

**Comment by maknesium** [comment]
Hi @sineadsayo , ich schaue mir das gerne an. Kannst du mir erklären was du genau meinst mit "Wenn man die "Hauptdatei.tex" ein paar mal **nacheinander öffnet**..."

Welchen Editor und welche Tex Distribution verwendest du denn?

**Comment by sineadsayo** [comment]
Hi, ich verwende TeXShop. Ich meine damit, dass der Fehler erst auftritt, wenn man die sich die "Hauptdatei.tex" ein paar mal rendern lässt als pdf (ohne etwas am Code zu ändern). Beim ersten Öffnen ist der Fehler noch nicht aufgetreten. Ich hoffe du kannst den Fehler reproduzieren, ansonsten scheint es einen Fehler in meiner Anwendung zu geben 🤷

**Comment by maknesium** [comment]
Kann du die mitgelieferte Hauptdatei.pdf mal löschen und schauen ob beim ersten Rendering dann eine korrekte Hauptdatei.pdf erzeugt wird?

Ansosnten würde ich empfehlen, dass du einmal das script "generatePdf.sh" im scripts Verzeichnis ausführst um zu schauen ob dies eine korrekte PDF Datei erzeugt.

Für TeXShop sind noch weitere Dateien (die starten alle mit .Punkt) notwendig damit das Template verwendet werden kann. Da nur TeXShop diese benötigt, habe ich diese weggelassen.

**Comment by maknesium** [comment]
@sineadsayo , ich gehe davon aus, dass das Problem bei dir lokal aufgetreten ist. Wenn du es reproduzieren kannst, melde dich bitte nochmals.
