### ISSUE TITLE
Implement a glossary

### ISSUE THREAD

**Issue by PerianezTroya** [maknesium/latex-vorlage-diplom-bachelor-masterarbeiten#10]
Is it possible to implement a glossary in the latex template?
Thanks in advance.
Regards José

**Comment by maknesium** [comment]
Please see the "\printnomenclature" section in Hauptdatei.tex file (line 246) and the abbreviations / glossary can be placed into the file "latex_einstellungen/abkuezungen/abkuerzungen".

Just look around for the term "glossary" in Hauptdatei.tex and you should find all necessary info :)
