### ISSUE TITLE
Abkürzungsverzeichnis wird nicht eingebunden

### ISSUE THREAD

**Issue by eibrahi** [maknesium/latex-vorlage-diplom-bachelor-masterarbeiten#4]
Hallo,

ich habe deine Vorlage runtergeladen und diese sofort Übersetzt dabei habe ich festgestellt das er zwar das Abkürzungsverzeichnis im Inhaltsverzeichnis listet jedoch nicht mit römischen Zahlen sondern mit arabischen und das eigentliche Abkürzungsverzeichnis wird überhaupt nicht übersetzt/dargestellt.
Habe ewig am Problem gesucht konnte leider keine Lösung finden.

**Comment by Garfield313** [comment]
Hey,
ich hatte das Problem ebenfalls.
Damit das Abkürzungsverzeichnis richtig funktioniert, muss das Projekt zuerst einmal kompiliert werden. Anschließend die Kommandozeile (Eingabeaufforderung (CMD)) aufrufen und mittels cd... in das Projektverzeichnis wechseln. Danach folgenden Befehl eingeben: "makeindex Hauptdatei.nlo -s nomencl.ist -o Hauptdatei.nls". Beim nächsten Kompilieren sollte das Abkürzungsverzeichnis zu sehen sein.
