### ISSUE TITLE
Hyperlinks im Inhaltsverzeichnis sind "verschoben"

### ISSUE THREAD

**Issue by isThatHim** [maknesium/latex-vorlage-diplom-bachelor-masterarbeiten#6]
Hallo!
Ich habe deine Vorlage runtergeladen und bin begeistert.
Allerdings ist mir aufgefallen, dass die Hyperlinks im Inhaltsverzeichnis nicht auf die korrekten Einträge im PDF "zeigen".
Zum Beispiel wird beim klicken auf "Abbildungsverzeichnis" die Seite mit dem Inhaltsverzeichnis angezeigt, beim klicken auf "Tabellenvereichnis" dann die Seite mit dem Abbildungsverzeichnis.

Dies passiert auch in der schon im Git-Repo vorhandenen Originaldatei.

Ich weiß leider nicht, wie ich dieses Problem lösen kann und würde mich über Hilfe freuen.

EDIT: Dieses Problem gilt anscheinend nur für die Hyperlinks auf Überschriften vor der Einleitung (die mit römischen Zahlen numerierten Einträge).

**Comment by maknesium** [comment]
Hi, das Problem sollte jetzt gelöst sein.

Quelle für die Lösung: https://tex.stackexchange.com/a/574769
