### ISSUE TITLE
Abkuerzungen werden nicht angezeigt

### ISSUE THREAD

**Issue by tbrodbeck** [maknesium/latex-vorlage-diplom-bachelor-masterarbeiten#9]
Ich habe versucht mir das PDF mit LaTeX Workshop von VSCode und mit `generatePdf.sh` zu kompilieren. Es hat alles geklappt, bis auf das Abkuerzungsverzeichnis. Das fehlt in meiner Version.

Ich habe auch versucht das ganze mit Docker zu kompilieren, aber bei mir erzeugt der Container ueberhaupt keinen Output.

**Comment by maknesium** [comment]
Hallo, bitte stelle sicher, dass du "makeindex" korrekt installiert hast in deiner Umgebung. Um den Fehler zu finden kannst du die Befehle aus der generatePdf.sh einzel ausführen und schauen, ob du Fehlermeldungen erhältst und diese hier posten.

Ich habe zum Dockerfile nochmal explizit das Paket "texlive-base" hinzugefügt, welches "makeindex" enthält. Es ist also in jedem Fall installiert.

**Comment by srcmkr** [comment]
Ich habe das selbe Problem. Es wird folgender Fehler geworfen:
`Latexmk: Missing input file: 'Hauptdatei.nls' from following:
  'No file Hauptdatei.nls.'`

Wenn ich versuche die nls Datei manuell zu erstellen `makeindex Hauptdatei.tex -s .\latex_einstellungen\abkuezungen\nomencl.ist -o Hautpdatei.nls` kommt nur folgende Ausgabe:
`
This is makeindex, version 2.15 [TeX Live 2021/W32TeX] (kpathsea + Thai support).
Scanning style file ./latex_einstellungen/abkuezungen/nomencl.ist..........done (10 attributes redefined, 3 ignored).
Scanning input file Hauptdatei.tex...done (0 entries accepted, 196 rejected).
Nothing written in Hautpdatei.nls.
Transcript written in Hauptdatei.ilg
`

**Comment by srcmkr** [comment]
Nachtrag ;)

@tbrodbeck das Problem scheint bereits gelöst zu sein ( in #4 )
Einfach einmalig die Datei "initialisieren" / anlegen via `makeindex Hauptdatei.nlo -s nomencl.ist -o Hauptdatei.nls`
(im Ordner /src auszuführen)

Dann klappt alles und das Abkürzungsverzeichnis ist da.

**Comment by maknesium** [comment]
@srcmkr Vielen Dank für den Hinweis. Bei mir (texlive Distribution auf Linux Mint 20) tritt der Fehler nach wie vor nicht auf aber ich würde das `generatePdf.sh` Script gerne so erweitern, dass der Fall abgefangen wird. Dafür fehlen mir aber noch die Infos, welche (fehlende) Datei genau den Fehler produziert.

Dein Befehl im Kommentar lautet `makeindex Hauptdatei.tex .....` jedoch muss man hier die NLO Datei angeben wie auch im Script gemacht mit `makeindex Hauptdatei.nlo ....` und ich erhalte dann die Ausgabe:
`makeindex Hauptdatei.nlo -s latex_einstellungen/abkuezungen/nomencl.ist -o Hauptdatei.nls
This is makeindex, version 2.15 [TeX Live 2019] (kpathsea + Thai support).
Scanning style file ./latex_einstellungen/abkuezungen/nomencl.ist..........done (10 attributes redefined, 3 ignored).
Scanning input file Hauptdatei.nlo....done (19 entries accepted, 0 rejected).
Sorting entries....done (90 comparisons).
Generating output file Hauptdatei.nls....done (40 lines written, 0 warnings).
Output written in Hauptdatei.nls.
Transcript written in Hauptdatei.ilg.`

In Zeile 11 des `generatePdf.sh` Scripts wird ja bereits die Hautpdatei.nls erzeugt. Von daher wüsste ich nicht, was fehlen sollte.

**Comment by tbrodbeck** [comment]
Zu meinem aktuellen Workaround oder als Empfehlung: Ich bin jetzt auf das `acronym` Packet heruebergewechselt. Das bringt auch noch ein paar zusaetzliche Funktionalitätet mit sich mit
```
\begin{acronym}[MAAPES]
  \acro{ADAM}{Adaptive Moment Estimation}
  \acro{AI}{Artificial Intelligence}
  \acro{ANN}{Artificial Neural Network}
  \acro{ARIMA}{Autoregressive Integrated Moving Average}
[....]
  \acro{S2SD}{Sequence-to-Sequence Dense Model}
\end{acronym}
```

**Comment by maknesium** [comment]
@tbrodbeck okay, man könnte wirklich überlegen, die Vorlage zu migrieren.

Dennoch würde ich gerne das `generatePdf.sh` Script so anpassen, dass Fehler des Tickets, nämlich das beim ersten Kompilieren kein Inhaltsverzeichnis generiert wird, gelöst wird.

@srcmkr , @tbrodbeck Habt ihr noch Infos wie man das ursprüngliche Problem nachstellen kann? Dann mache ich einen Fix.

**Comment by srcmkr** [comment]
Es wird daran liegen, dass @tbrodbeck und ich nicht das docker-image nutzen, sondern einfach den Branch auschecken und mit einer lokalen Installation von latex arbeiten. Sprich: Da wird einfach nichts an Scripten ausgeführt, wenn wir abspeichern und uns das Preview anschauen :) (LaTeX Workshop Extension für Visual Studio Code).   
Es liegt mMn auch kein Fehler vor, sondern nur die Notwendigkeit eines Workarounds zum Generieren des Inhaltsverzeichnisses, wenn man ohne docker arbeitet. Eventuell wäre es etwas für die Doku.

**Comment by maknesium** [comment]
Super, vielen Dank! Ich habe die Dokumentation erweitert und einen Teil für "LaTeX Workshop Extension für Visual Studio Code" hinzugefügt.
